# Generated by Django 4.2.4 on 2023-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content_rating', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('theme', models.CharField(max_length=100)),
                ('runtime', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
